// <auto-generated />
namespace BulletinHub.Contexts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TempDb_8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TempDb_8));
        
        string IMigrationMetadata.Id
        {
            get { return "201805281143255_TempDb_8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
