// <auto-generated />
namespace BulletinHub.Contexts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TempDb_7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TempDb_7));
        
        string IMigrationMetadata.Id
        {
            get { return "201805211123576_TempDb_7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
