// <auto-generated />
namespace BulletinHub.Contexts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TempDb_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TempDb_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201805301420465_TempDb_10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
