// <auto-generated />
namespace BulletinEngine.Contexts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BulletinDb_28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BulletinDb_28));
        
        string IMigrationMetadata.Id
        {
            get { return "201805281131223_BulletinDb_28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
